[package]
name = "training"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
pixel_core = { path = "../pixel_core" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true

